version: '3.7'
services:
  reverse-proxy:
    image: nginx # /!\ preciser la version x:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 880:80
    networks:
      - web
networks:
  web:
    external: true
